---
mode: 
  ManualWinch: 0
controller_addr: "10.32.0.1:9024"
flyer_addr: "10.32.0.8:9024"
web: 
  http_addr: "10.0.0.5:8080"
  ws_addr: "10.0.0.5:8081"
  web_root_path: web/build
  connection_file_path: connection.txt
params: 
  manual_control_velocity_m_per_sec: 0.34
  accel_limit_m_per_sec2: 0.44
  force_neg_motion_min_kg: 0.29
  force_pos_motion_max_kg: 3.89
  force_lockout_below_kg: 0.1
  force_lockout_above_kg: 4
  force_filter_param: 0.0402
  deadband_position_err_m: 0.006
  deadband_velocity_limit_m_per_sec: 0.0352
  pos_err_filter_param: 0.05898
  vel_err_filter_param: 0.007999
  integral_err_decay_param: 0.002199
  pwm_gain_p: 1.33
  pwm_gain_i: 3.346
  pwm_gain_d: 4.33465
lighting: 
  animation: 
    frame_rate: 160
    filter_param: 0.04
  current: 
    brightness: 1
    flash_rate_hz: 3
    flash_exponent: 0.7
    winch: 
      wavelength_m: 0.2
      normal_color: 
        - 0
        - 0.2
        - 0
      error_color: 
        - 1
        - 0
        - 0
      stuck_color: 
        - 0.5
        - 0
        - 0
      halt_color: 
        - 0.2
        - 0.2
        - 0
      manual_color: 
        - 0
        - 0
        - 0.8
      command_color: 
        - 1
        - 0
        - 0
      motion_color: 
        - 0
        - 1
        - 1
      wave_amplitude: 4
      wave_exponent: 8
      speed_for_full_wave_amplitude_m_per_sec: 0.4
      velocity_filter_param: 0.01
  saved: {}
  schedule: []
winches: 
  - 
    addr: "10.32.0.10:9024"
    loc: 
      - 10
      - 10
      - 0
    calibration: 
      force_zero_count: -110492.545
      kg_force_per_count: 0.000002666225139307698
      m_dist_per_count: 0.000033002937261416265
  - 
    addr: "10.32.0.11:9024"
    loc: 
      - 10
      - -10
      - 0
    calibration: 
      force_zero_count: 0
      kg_force_per_count: 1
      m_dist_per_count: 1
  - 
    addr: "10.32.0.12:9024"
    loc: 
      - -10
      - -10
      - 0
    calibration: 
      force_zero_count: 0
      kg_force_per_count: 1
      m_dist_per_count: 1
  - 
    addr: "10.32.0.13:9024"
    loc: 
      - -10
      - 10
      - 0
    calibration: 
      force_zero_count: 0
      kg_force_per_count: 1
      m_dist_per_count: 1