---
mode: 
  ManualWinch: 0
controller_addr: "10.32.0.1:9024"
flyer_addr: "10.32.0.8:9024"
web: 
  http_addr: "10.0.0.5:8080"
  ws_addr: "10.0.0.5:8081"
  web_root_path: web/build
  connection_file_path: connection.txt
params: 
  manual_control_velocity_m_per_sec: 0.4
  force_neg_motion_min_kg: 0.29
  force_pos_motion_max_kg: 3.89
  force_lockout_below_kg: 0.1
  force_lockout_above_kg: 4
  force_filter_param: 0.0402
  vel_err_filter_param: 0.085691
  pwm_gain_p: 3.141
  pwm_gain_i: 0.038
  pwm_gain_d: 0.0067
winches: 
  - 
    addr: "10.32.0.10:9024"
    loc: 
      - 10
      - 10
      - 0
    calibration: 
      force_zero_count: -110492.545
      kg_force_per_count: 0.000002666225139307698
      m_dist_per_count: 0.000033002937261416265
  - 
    addr: "10.32.0.11:9024"
    loc: 
      - 10
      - -10
      - 0
    calibration: 
      force_zero_count: 0
      kg_force_per_count: 1
      m_dist_per_count: 1
  - 
    addr: "10.32.0.12:9024"
    loc: 
      - -10
      - -10
      - 0
    calibration: 
      force_zero_count: 0
      kg_force_per_count: 1
      m_dist_per_count: 1
  - 
    addr: "10.32.0.13:9024"
    loc: 
      - -10
      - 10
      - 0
    calibration: 
      force_zero_count: 0
      kg_force_per_count: 1
      m_dist_per_count: 1